name: release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')

    runs-on: ubuntu-latest

    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configurationJson: |
            {
                "template": "#{{CHANGELOG}}\n\n<details>\n<summary>",
                "pr_template": "- #{{TITLE}} ##{{NUMBER}} (Thanks @#{{AUTHOR}})",
                "categories": [
                    {
                        "title": "## Features",
                        "labels": ["feature"]
                    },
                    {
                        "title": "## Fixes",
                        "labels": ["fix"]
                    },
                    {
                        "title": "## Other",
                        "labels": ["other"]
                    }
                ]
            }

      - name: Create Release
        id: create_release
        uses: mikepenz/action-gh-release@v0.2.0-a03
        with:
          body: ${{steps.github_release.outputs.changelog}}
          draft: true
